# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
script:
  - bash deploy.sh
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libgdal-dev
on:
  all_branches: true
  condition: $TRAVIS_BRANCH =~ ^master|develop$
