---
title: "Events by State"
site: workflowr::wflow_site
output: workflowr::wflow_html
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, 
  warning = TRUE, 
  error = TRUE, 
  fig.width = 10, 
  fig.asp = 1, 
  fig.dpi = 180
)
```

```{r libraries}
library(glue)
library(lubridate)
library(tidyverse)
```

```{r data}
details <- 
  read_csv(
    file = here::here("./output/details.csv"), 
    col_types = cols(
      .default = col_character(),
      EPISODE_ID = col_integer(), 
      EVENT_ID = col_integer(),
      STATE_FIPS = col_integer(),
      CZ_FIPS = col_integer(),
      BEGIN_DATE_TIME = col_datetime(format = ""),
      END_DATE_TIME = col_datetime(format = ""),
      INJURIES_DIRECT = col_integer(),
      INJURIES_INDIRECT = col_integer(),
      DEATHS_DIRECT = col_integer(),
      DEATHS_INDIRECT = col_integer(),
      DAMAGE_PROPERTY = col_number(),
      DAMAGE_CROPS = col_number(),
      MAGNITUDE = col_double(),
      TOR_LENGTH = col_double(),
      TOR_WIDTH = col_double(),
      BEGIN_RANGE = col_integer(),
      END_RANGE = col_integer(),
      BEGIN_LAT = col_double(),
      BEGIN_LON = col_double(),
      END_LAT = col_double(),
      END_LON = col_double()
    )
  )

event_types <- 
  read_csv(
    file = here::here("./output/event_types.csv"), 
    col_types = cols(
      EPISODE_ID = col_number(), 
      EVENT_ID = col_number(), 
      EVENT_TYPE = col_character()
    )
  )
```

### Events by state

```{r state-events}
details %>% 
  group_by(STATE) %>% 
  summarise(Events = n()) %>% 
  mutate(STATE = fct_reorder(STATE, Events)) %>% 
  ungroup() %>% 
  ggplot() + 
  aes(x = STATE, y =  Events) + 
  geom_col() + 
  scale_y_continuous(labels = scales::comma) + 
  coord_flip() + 
  labs(
    title = "Total Events by State", 
    subtitle = glue(
      "{min(year(details$BEGIN_DATE_TIME))} - {max(year(details$END_DATE_TIME))}"
    ), 
    x = "State"
  )
```

### Types of events

```{r event-types}
event_types %>% 
  group_by(EVENT_TYPE) %>% 
  summarise(Total = n()) %>% 
  mutate(EVENT_TYPE = fct_reorder(EVENT_TYPE, Total)) %>% 
  ungroup() %>% 
  ggplot() + 
  aes(x = EVENT_TYPE, y = Total) + 
  geom_col() + 
  scale_y_continuous(labels = scales::comma) + 
  coord_flip() + 
  labs(
    title = "Event Types", 
    subtitle = glue(
      "{min(year(details$BEGIN_DATE_TIME))} - {max(year(details$END_DATE_TIME))}"
    ), 
    x = "Event Types"
  )
```

### Events by year

```{r events-by-year}
details %>% 
  group_by(Year = year(BEGIN_DATE_TIME)) %>% 
  summarise(Events = n()) %>% 
  ggplot() + 
  aes(x = Year, y = Events) + 
  geom_col() + 
  scale_x_continuous(
    breaks = seq(1950, 2020, by = 10), 
    minor_breaks = seq(1950, 2020, by = 5)
  ) +
  scale_y_continuous(labels = scales::comma) + 
  coord_flip() + 
  labs(
    title = "Events by Year"
  )
```

### Events by type, month

```{r events-by-month, message = FALSE, fig.asp = 1.5}
set.seed(10L)
details %>% 
  sample_n(size = 1000L) %>% 
  select(EVENT_ID, BEGIN_DATE_TIME) %>% 
  left_join(event_types, by = "EVENT_ID") %>% 
  mutate(MONTH = month(BEGIN_DATE_TIME)) %>% 
  group_by(EVENT_TYPE, MONTH) %>% 
  summarise(EVENTS = n()) %>% 
  ungroup() %>% 
  #' Order facet plot by max `EVENTS` per `EVENT_TYPE`
  mutate(EVENT_TYPE = fct_reorder(
    .f = EVENT_TYPE, 
    .x = EVENTS, 
    .fun = max, 
    .desc = TRUE)
  ) %>% 
  #' Many `EVENTS` do not occur in some months. `dplyr` and `ggplot` will not 
  #' show these values as 0 but rather just connect a line between observations 
  #' which leads to a misleading chart. Need to add a default 0 value for every 
  #' missing `MONTH` in the dataset.
  #' See: https://kieranhealy.org/blog/archives/2018/11/19/zero-counts-in-dplyr/
  complete(EVENT_TYPE, nesting(MONTH), fill = list(EVENTS = 0)) %>% 
  ggplot() + 
  aes(x = MONTH, y = EVENTS) + 
  geom_line() + 
  geom_point() + 
  facet_wrap(~EVENT_TYPE, ncol = 4L, scales = "free_y") + 
  scale_x_continuous(
    labels = month.abb, 
    breaks = seq(1, 12, by = 1), 
    minor_breaks = NULL
  ) +
  scale_y_continuous(
    #' Do not show doubles along y-axis
    breaks = function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1)))), 
    #' Add a little cushion to top but none at bottom
    expand = expand_scale(mult = c(0, multi = 0.5))
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + 
  labs(
    title = "Events by Month, Event Type", 
    subtitle = "In order of most active events"
  )
```

