---
title: "Injuries and Fatalities"
author: "Tim Trice"
date: "2019-03-03"
output: workflowr::wflow_html
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE, 
  warning = TRUE, 
  error = TRUE, 
  fig.width = 10, 
  fig.asp = 1, 
  fig.dpi = 180
)
```

```{r libraries}
library(lubridate)
```

```{r data}
details <- 
  read_csv(
    file = here::here("./output/details.csv"), 
    col_types = cols(
      .default = col_character(),
      EPISODE_ID = col_integer(), 
      EVENT_ID = col_integer(),
      STATE_FIPS = col_integer(),
      CZ_FIPS = col_integer(),
      BEGIN_DATE_TIME = col_datetime(format = ""),
      END_DATE_TIME = col_datetime(format = ""),
      INJURIES_DIRECT = col_integer(),
      INJURIES_INDIRECT = col_integer(),
      DEATHS_DIRECT = col_integer(),
      DEATHS_INDIRECT = col_integer(),
      DAMAGE_PROPERTY = col_number(),
      DAMAGE_CROPS = col_number(),
      MAGNITUDE = col_double(),
      TOR_LENGTH = col_double(),
      TOR_WIDTH = col_double(),
      BEGIN_RANGE = col_integer(),
      END_RANGE = col_integer(),
      BEGIN_LAT = col_double(),
      BEGIN_LON = col_double(),
      END_LAT = col_double(),
      END_LON = col_double()
    )
  )

fatalities <- 
  read_csv(
    file = here::here("./output/fatalities.csv"), 
    col_types = cols()
  )
```

## Injuries by year

```{r injuries-year, fig.asp = 0.5}
details %>% 
  mutate(YEAR = year(BEGIN_DATE_TIME)) %>%
  select(YEAR, INJURIES_DIRECT, INJURIES_INDIRECT) %>% 
  group_by(YEAR) %>% 
  summarise(
    INJURIES_DIRECT = sum(INJURIES_DIRECT, na.rm = TRUE), 
    INJURIES_INDIRECT = sum(INJURIES_INDIRECT, na.rm = TRUE)
  ) %>% 
  gather(key = "TYPE", value = "INJURIES", starts_with("INJURIES")) %>% 
  ggplot() + 
  aes(x = YEAR, y = INJURIES, color = TYPE) + 
  geom_line() + 
  scale_x_continuous(
    breaks = seq(1950, 2020, by = 10), 
    minor_breaks = seq(1950, 2020, by = 5)
  ) + 
  scale_y_continuous(labels = scales::comma) + 
  theme(legend.position = "bottom") + 
  labs(
    title = "Injuries by Year", 
    x = "Year", 
    y = "Injuries"
  )
```

## Injuries by month

```{r injuries-month, fig.asp = 0.5}
details %>% 
  mutate(MONTH = month(BEGIN_DATE_TIME)) %>%
  select(MONTH, INJURIES_DIRECT, INJURIES_INDIRECT) %>% 
  group_by(MONTH) %>% 
  summarise(
    INJURIES_DIRECT = sum(INJURIES_DIRECT, na.rm = TRUE), 
    INJURIES_INDIRECT = sum(INJURIES_INDIRECT, na.rm = TRUE)
  ) %>% 
  gather(key = "TYPE", value = "INJURIES", starts_with("INJURIES")) %>% 
  ggplot() + 
  aes(x = MONTH, y = INJURIES, color = TYPE) + 
  geom_line() + 
  scale_x_continuous(
    labels = month.abb, 
    breaks = seq(1, 12, by = 1)
  ) + 
  scale_y_continuous(labels = scales::comma) + 
  theme(legend.position = "bottom") + 
  labs(
    title = "Injuries by Month", 
    x = "Month", 
    y = "Injuries"
  )
```

## Fatalities

## Fatalities by Year

```{r fatalities-year, fig.asp = 0.5}
fatalities %>% 
  mutate(YEAR = year(FATALITY_DATE_TIME_1)) %>% 
  group_by(YEAR, FATALITY_TYPE) %>% 
  summarise(n_FATALITIES = n()) %>%
  ggplot() + 
  aes(x = YEAR, y = n_FATALITIES, color = FATALITY_TYPE) + 
  geom_line() + 
  scale_x_continuous(
    breaks = seq(1950, 2020, by = 10), 
    minor_breaks = seq(1950, 2020, by = 5)
  ) + 
  scale_y_continuous(labels = scales::comma) + 
  theme(legend.position = "bottom") + 
  labs(
    title = "Fatalities by Year", 
    x = "Year", 
    y = "Fatalities"
  )
```

## Fatalities by Month

```{r fatalities-month, fig.asp = 0.5}
fatalities %>% 
  mutate(MONTH = month(FATALITY_DATE_TIME_1)) %>% 
  group_by(MONTH, FATALITY_TYPE) %>% 
  summarise(n_FATALITIES = n()) %>% 
  filter(!is.na(MONTH)) %>% 
  ggplot() + 
  aes(x = MONTH, y = n_FATALITIES, color = FATALITY_TYPE) + 
  geom_line() + 
  scale_x_continuous(
    labels = month.abb, 
    breaks = seq(1, 12, by = 1)
  ) + 
  scale_y_continuous(labels = scales::comma) + 
  theme(legend.position = "bottom") + 
  labs(
    title = "Fatalities by Month", 
    x = "Month", 
    y = "Fatalities"
  )
```

## Fatalities by Age

```{r fatalities-age, fig.asp = 0.5}
fatalities %>% 
  group_by(FATALITY_AGE, FATALITY_TYPE) %>% 
  summarise(n = n()) %>% 
  ggplot() + 
  aes(x = FATALITY_AGE, y = n, fill = FATALITY_TYPE) + 
  geom_col() + 
  scale_x_continuous(
    breaks = seq(0, 110, by = 10), 
    minor_breaks = seq(0, 110, by = 5)
  ) + 
  theme(legend.position = "bottom") + 
  labs(
    title = "Fatalities by Age", 
    x = "Age", 
    y = "Fatalities"
  )
```

## Fatalities by Sex

```{r fatalities-sex, fig.asp = 0.5}
fatalities %>% 
  group_by(FATALITY_SEX, FATALITY_TYPE) %>% 
  summarise(n = n()) %>% 
  ggplot() + 
  aes(x = FATALITY_SEX, y = n, fill = FATALITY_TYPE) + 
  geom_col() + 
  scale_y_continuous(labels = scales::comma) +
  theme(legend.position = "bottom") + 
  labs(
    title = "Fatalities by Sex", 
    x = "Sex", 
    y = "Fatalities"
  )
```
